### PR TITLE
Create new team with pro plan subscription

### PR DESCRIPTION
**Pull request by satococoa**
## Summary
Implemented the feature for creating new teams.
There are three types of teams:

- Free team
- Pro team
- Internal team (This will be treated as Pro team on UI)

Because pro team requires a subscription, creating a Pro team is a bit tricky.

- services/teams/actions/create-team.ts
  - Set the team's name, userDbId in metadata of stripe checkout session.
  - Create a Stripe checkout session
- app/webhooks/stripe/route.ts
  - Receive webhook
  - If subscription data is not in Giselle's database, create a Team and Membership using the data from the metadata, then create a subscription record.

### What I have NOT done
These features will come later in another pull request:

- Selecting a team
- Upgrading an existing team

#### ROUTE06 Internal User Flow
- [x] Test with `@route06.co.jp` email
  - [x] Create Pro team
  - [x] Verify team type is set to "internal"
  - [x] Confirm no Stripe checkout redirect

#### External User Flow (Pro)
- [x] Test with `@giselles.ai` email
  - [x] Attempt Pro team creation
  - [x] Verify Stripe checkout page redirect
  - [x] Confirm subscription creation
  - [x] Verify team creation with correct type

Note: Use local webhook listener with Stripe CLI.

#### External User Flow (Free)
- [x] Test with `@giselles.ai` email
  - [x] Create Free team
  - [x] Verify team type is "customer"
  - [x] Confirm no Stripe interaction
  
Note: Free team testing requires code modification for testing purposes.

#### Route06 Internal User Flow
- [x] Repeat internal user flow as above
  - [x] Verify team type consistency

#### External User Flow (Pro)
- [x] Repeat pro user flow as above
  - [x] Verify Stripe integration
  - [x] Confirm subscription creation

Note: must set `NEXT_PUBLIC_SITE_URL` to this branch's preview URL.

#### Stripe webhook endpoint
- [x] Add this PR's URL ( https://giselle-git-create-new-team-with-pro-plan-subscription-r06-edge.vercel.app/ )
- [x] Add STRIPE_WEBHOOK_SECRET for ⬆️ 
- [ ] After the merging this PR, create preview branch from main branch and push
  - This will publish https://giselle-git-preview-r06-edge.vercel.app
- [ ] After the merging this PR, remove PR's URL ( https://giselle-git-create-new-team-with-pro-plan-subscription-r06-edge.vercel.app/ )

#### Vercel Environment values for Preview and Development
- [x] Add `STRIPE_PRO_PLAN_PRICE_ID`
- [x] Add `STRIPE_AGENT_TIME_CHARGE_PRICE_ID`
- [x] Add `STRIPE_USER_SEAT_PRICE_ID`

#### Vercel Environment values for Production
We have not decided on the prices of plans yet.
So for now, we'll add these prices as dummy values.

- [x] Add `STRIPE_PRO_PLAN_PRICE_ID` as a dummy
- [x] Add `STRIPE_AGENT_TIME_CHARGE_PRICE_ID` as a dummy
- [x] Add `STRIPE_USER_SEAT_PRICE_ID` as a dummy

### CODE REVIEW

**Comment by satococoa** [comment]
Do we really need the `draftTeam`??

With [metadata](https://docs.stripe.com/api/metadata), we can do:

> You can specify up to 50 keys, with key names up to 40 characters long and values up to 500 characters long.

Therefore is adding team name and creator's user.dbId is enough?

**Review by shige — APPROVED** [review]
LGTM! 👍 

I will do my OATs in https://giselle-git-preview-r06-edge.vercel.app.

**Comment by satococoa** [comment]
@toyamarinyon 

> Please tell me why you have added `DRAFT_TEAM_NAME_METADATA_KEY` and `DRAFT_TEAM_USER_DB_ID_METADATA_KEY` ?

We need to handle the team creation flow with Stripe integration. Here's why:

1. Data Flow Requirements:
   - Team creation requires storing: team name + creator's information
   - Stripe checkout → webhook flow needs to identify:
     - Who initiated the team creation
     - What team name they wanted
   - Inserting subscription record needs `teams.dbId`.

2. Solution Consideration:
   - Initially considered adding `draftTeam` table to database
     - This needs `draftTeam.dbId` to be stored in metadata anyway.
   - Simplified approach: Store necessary information in Stripe metadata

```ts
const subscriptionMetadata: Record<string, string> = {
	[DRAFT_TEAM_USER_DB_ID_METADATA_KEY]: userDbId.toString(),
	[DRAFT_TEAM_NAME_METADATA_KEY]: teamName,
};
```

Storing in Stripe metadata is sufficient because:

- Temporary data only needed during checkout flow
- No need for additional database table
- Webhook can access all necessary information

Will implement this approach in the checkout URL creation.

**Review by toyamarinyon — APPROVED** [review]
I've reviewed the approach of using Stripe metadata for storing draft team information. While I considered several alternatives, I agree with the current implementation. Here's my analysis:

Possible alternatives considered:

1. Using a `draft_teams` table:
   - Pros: Type safety, better tracking, easy cleanup via expiration
   - Cons: Additional table maintenance, requires migration

2. Using Redis/memory cache:
   - Pros: Suitable for temporary data, fast, auto-expiry
   - Cons: Additional infrastructure needed

3. Using JWT tokens:
   - Pros: No extra infrastructure, tamper-proof
   - Cons: Token size limitations, more complex token management

Current approach (Stripe metadata) is sufficient because:
- It's simple and requires no additional infrastructure
- The data is temporary and only needed during checkout flow
- All necessary information is available in webhooks
- Implementation is straightforward and maintainable

For the current requirements, the Stripe metadata approach provides a good balance of simplicity and functionality. If we need more complex tracking or analysis in the future, we can consider migrating to a `draft_teams` table.

LGTM 👍

**Comment by satococoa** [comment]
Thank you for your reviews.
I'll merge this and do these todos.

- [x] After the merging this PR, create preview branch from main branch and push
  - This will publish https://giselle-git-preview-r06-edge.vercel.app/
- [x] After the merging this PR, remove PR's URL ( https://giselle-git-create-new-team-with-pro-plan-subscription-r06-edge.vercel.app/ )

**Comment by satococoa** [comment]
@shige 
I've updated this preview environment:
https://giselle-git-preview-r06-edge.vercel.app

**Comment by shige** [comment]
@satococoa Thanks, I will check it later!

**Comment by satococoa** [comment]
I've verified on https://giselle-git-preview-r06-edge.vercel.app/ ✅ 

- [x] Route06 Internal User Flow
  - [x] Repeat internal user flow as above
  - [x] Verify team type consistency
- [x] External User Flow (Pro)
  - [x] Repeat pro user flow as above
  - [x] Verify Stripe integration
  - [x] Confirm subscription creation

**Pull request merged**
