### PR TITLE
[DO NOT MERGE UNTIL 2024/12/26] Activate free plan

### PR DESCRIPTION
**Pull request by satococoa**
## Summary
This pull request will release the free plan.
Users can sign up as a free team member and can use Giselle for 30 minutes per month.

## Changes
- Re-display signup link
- Fix wrong flag condition to hide `/settings/billing`
- Enable freePlan feature flag
- Change agent time limit for free plan team

## Testing
- [x] Users can signup
- [x] Pro plan is not available
- [x] Users can create, run agent
- [x] Agent usage is saved in database
- [x] Users can see agent time usage on `/settings/team`
- [x] Internal user can use Giselle as a Pro plan member

### CODE REVIEW

**Review by shige — APPROVED** [review]
LGTM! 🆓

**Review by toyamarinyon — APPROVED** [review]

**Comment by satococoa** [comment]
Before release...

- [x] merge main into this branch
- [x] self OAT on preview: ~https://giselle-v50awndax-r06-edge.vercel.app/login~ https://giselle-2gaw6cwgf-r06-edge.vercel.app/

## self OAT
- [x] Users can signup
- [x] Pro plan is not available
- [x] Users can create, run agent
- [x] Agent usage is saved in database
- [x] Users can see agent time usage on /settings/team
- [x] Internal user can use Giselle as a Pro plan member

**Comment by satococoa** [comment]
🐛 While doing OAT myself, I found a bug (possibly caused by another PR).
I'll release this PR after fixing https://github.com/giselles-ai/giselle/issues/276.

**Comment by satococoa** [comment]
📝 After merging #277, I'll continue my OATs.

**Comment by satococoa** [comment]
I'll release this now 🚀

**Pull request merged**
