### PR TITLE
[feat] Add file removal functionality with improved UI feedback

### PR DESCRIPTION
**Pull request by toyamarinyon**
https://github.com/user-attachments/assets/88cc6df6-08e9-42c0-95fa-985da4792b38

### Changes
- Add hover-triggered delete button with tooltip to file list items
- Implement file removal functionality through state management
- Update file list item styling with hover states and transitions
- Add visual feedback for delete button interactions

### CODE REVIEW

**Comment by shige** [comment]
@toyamarinyon 

It seems that the file itself has not been deleted from storage and is only removed on the UI. Do you plan to implement this separately?  

https://vercel.com/docs/storage/vercel-blob/using-blob-sdk#delete-a-blob

**Comment by toyamarinyon** [comment]
@shige  Oh, I forgot. I'll implement it  in this Pull request.

**Comment by toyamarinyon** [comment]
I've implemented with 3665d6bdb6000dc3b213621950cb00d8d73a6325

**Comment by toyamarinyon** [comment]
@shige ↑↑

**Review by shige — APPROVED** [review]
LGTM! 🗑️

**Pull request merged**
