### PR TITLE
Prevent redirection of non-subscribed users when free plan flag is enabled

### PR DESCRIPTION
**Pull request by satococoa**
## Summary
This PR enables users to use Giselle without a subscription.

- Limitations of the free plan will be implemented in other pull requests.
- Normal users won't be affected by this PR because of the feature flag.

### CODE REVIEW

**Review by toyamarinyon — APPROVED** [review]

**Review by shige — APPROVED** [review]
LGTM! 🎏

**Comment by satococoa** [comment]
Confirmed working properly in production environment. ✅

**Comment by satococoa** [comment]
@shige @toyamarinyon 
I'll revert this.
Internal users without free plan flag will redirect to /coming-soon page.

**Comment by shige** [comment]
OK 🙏

**Pull request merged**
