### PR TITLE
Update @vercel/flags

### PR DESCRIPTION
**Pull request by satococoa**
## Summary
To supress warning message like this: 

```
[Error: Route "/" used `cookies().get('vercel-flag-overrides')`. `cookies()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis]
```

## Related Issue
- https://github.com/giselles-ai/giselle/issues/12

### CODE REVIEW

**Review by toyamarinyon — APPROVED** [review]

**Review by shige — APPROVED** [review]
LGTM! 🆙

**Review by masutaka — APPROVED** [review]
@satococoa Thank you!
If possible, I would appreciate it if you could remove the following lines that are no longer needed in this PR!

https://github.com/giselles-ai/giselle/blob/ac8b6b8f218d1b388995218c12bdea828d805000/config/dependency_decisions.yml#L52-L58

**Comment by satococoa** [comment]
@masutaka 

I've edited [giselle/config/dependency_decisions.yml](https://github.com/giselles-ai/giselle/blob/ac8b6b8f218d1b388995218c12bdea828d805000/config/dependency_decisions.yml#L52-L58).

Could you please review these license permission updates?

**Review by masutaka — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
